version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: 7ga-service-mqtt
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      7ga-network:
        aliases:
          - "7ga-service-mqtt"
networks:
  7ga-network:
    name: 7ga-network
    ipam:
      driver: default
    external: true
    driver: bridge